name: Rust

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose --target x86_64-unknown-linux-musl --manifest-path rust/Cargo.toml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "rust/target/release/partition_id"
