name: Rust

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/cargo@v1
      working-directory: rust
      with:
        command: build
        args: --release --verbose
