name: Rust

defaults:
  run:
    shell: bash
    working-directory: rust

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/cargo@v1
      with:
        command: build --release --verbose
