name: Rust

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for release (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Stable with rustfmt and clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
        target: x86_64-unknown-linux-musl
    - uses: actions/checkout@v3
    - name: Install musl-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose --target x86_64-unknown-linux-musl --manifest-path rust/Cargo.toml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "rust/target/x86_64-unknown-linux-musl/release/partition_id"
        tag: ${{ inputs.tag }}
