name: Rust

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: rust
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
