name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - './rust/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - './rust/**'
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd rust && cargo build --release --verbose
    - name: Run tests
      run: cd rust && cargo test --verbose
